export const INTERVIEW_START = 'INTERVIEW_START';
export const INTERVIEW_PAUSE = 'INTERVIEW_PAUSE';
export const INTERVIEW_STOP = 'INTERVIEW_STOP';
export const INTERVIEW_NEXT = 'INTERVIEW_NEXT';
export const INTERVIEW_REPORT_SHOW = 'INTERVIEW_REPORT_SHOW';
export const INTERVIEW_REPORT_CLOSE = 'INTERVIEW_REPORT_CLOSE';
